from enum import IntEnum


class HandAction(IntEnum):
    PLAY_HAND = 0
    DISCARD = 1

class DeckCheck(IntEnum):
    CARDS = 0
    SCORE = 1

class Rank(IntEnum):
    TWO = 0
    THREE = 1
    FOUR = 2
    FIVE = 3
    SIX = 4
    SEVEN = 5
    EIGHT = 6
    NINE = 7
    TEN = 8
    JACK = 9
    QUEEN = 10
    KING = 11
    ACE = 12


class Suit(IntEnum):
    HEARTS = 0
    DIAMONDS = 1
    CLUBS = 2
    SPADES = 3


class Enhancement(IntEnum):
    NONE = -1
    STONE = 0
    GOLD = 1
    BONUS = 2
    MULT = 3
    WILD = 4
    LUCKY = 5
    GLASS = 6
    STEEL = 7


class Seal(IntEnum):
    NONE = -1
    GOLD = 0
    PURPLE = 1
    BLUE = 2
    RED = 3


class Edition(IntEnum):
    NONE = -1
    FOIL = 0
    HOLOGRAPHIC = 1
    POLYCHROME = 2


class JokerEdition(IntEnum):
    NONE = 0
    FOIL = 1
    HOLOGRAPHIC = 2
    POLYCHROME = 3
    NEGATIVE = 4


class Consumables(IntEnum):
    TAROT = 0
    PLANET = 1
    SPECTRAL = 2



class Tarot(IntEnum):
    FOOL = 0
    MAGICIAN = 1
    HIGH_PRIESTESS = 2
    EMPRESS = 3
    EMPEROR = 4
    HEIROPHANT = 5
    LOVERS = 6
    CHARIOT = 7
    JUSTICE = 8
    HERMIT = 9
    WHEEL_OF_FORTUNE = 10
    STENGHT = 11
    HANGED_MAN = 12
    DEATH = 13
    TEMPERANCE = 14
    DEVIL = 15
    TOWER = 16
    STAR = 17
    MOON = 18
    SUN = 19
    JUDGEMENT = 20
    WORLD = 21
    SOUL = 22


class Planet(IntEnum):
    ERIS = 0
    CERES = 1
    PLANET_X = 2
    MERCURY = 3
    VENUS = 4
    EARTH = 5
    MARS = 6
    JUPITER = 7
    SATURN = 8
    URANUS = 9
    NEPTUNE = 10
    PLUTO = 11
    BLACK_HOLE = 12


class Spectral(IntEnum):
    FAMILIAR = 0
    GRIM = 1
    INCANTATION = 2
    TALISMAN = 3
    AURA = 4
    WRAITH = 5
    SIGIL = 6
    OUIJA = 7
    ECTOPLASM = 8
    IMMOLATE = 9
    ANKH = 10
    DEJA_VU = 11
    HEX = 12
    TRANCE = 13
    MEDIUM = 14
    CRYPTID = 15



class CardFeatureTrainingType(IntEnum):
    RANK = 0
    SUIT = 1
    ENHANCEMENT = 2
    SEAL = 3
    EDITION = 4


class JokerFeatureTrainingType(IntEnum):
    JOKER_TYPE = 0
    JOKER_EDITION = 1


class PokerHand(IntEnum):
    HIGH_CARD = 1
    PAIR = 2
    THREE_OF_A_KIND = 3
    FOUR_OF_A_KIND = 4
    FIVE_OF_A_KIND = 5
    TWO_PAIR = 6
    STRAIGHT = 7
    FLUSH = 8
    FULL_HOUSE = 9
    STRAIGHT_FLUSH = 10
    FLUSH_HOUSE = 11
    FLUSH_FIVE = 12


class JokerTriggers(IntEnum):
    ON_PLAYED_CARDS = 0
    AFTER_HAND = 1
    ON_HELD_CARDS = 2
    BEFORE_PLAYED_CARDS = 3


class JokersName(IntEnum):
    JOKER = 0
    CHAOS_THE_CLOWN = 1
    JOLLY_JOKER = 2
    ZANY_JOKER = 3
    MAD_JOKER = 4
    CRAZY_JOKER = 5
    DROLL_JOKER = 6
    HALF_JOKER = 7
    MERRY_ANDY = 8
    STONE_JOKER = 9
    JUGGLER = 10
    DRUNKARD = 11
    ACROBAT = 12
    SOCK_AND_BUSKIN = 13
    MIME = 14
    CREDIT_CARD = 15
    GREEDY_JOKER = 16
    LUSTY_JOKER = 17
    WRATHFUL_JOKER = 18
    GLUTTONOUS_JOKER = 19
    TROUBADOUR = 20
    BANNER = 21
    MYSTIC_SUMMIT = 22
    MARBLE_JOKER = 23
    LOYALTY_CARD = 24
    HACK = 25
    MISPRINT = 26
    STEEL_JOKER = 27
    RAISED_FIST = 28
    GOLDEN_JOKER = 29
    BLUEPRINT = 30
    GLASS_JOKER = 31
    SCARY_FACE = 32
    ABSTRACT_JOKER = 33
    DELAYED_GRATIFICATION = 34
    GOLDEN_TICKET = 35
    PAREIDOLIA = 36
    CARTOMANCER = 37
    EVEN_STEVEN = 38
    ODD_TODD = 39
    SCHOLAR = 40
    BUSINESS_CARD = 41
    SUPERNOVA = 42
    MR_BONES = 43
    SEEING_DOUBLE = 44
    THE_DUO = 45
    THE_TRIO = 46
    THE_FAMILY = 47
    THE_ORDER = 48
    THE_TRIBE = 49
    X8_BALL = 50
    FIBONACCI = 51
    JOKER_STENCIL = 52
    SPACE_JOKER = 53
    MATADOR = 54
    CEREMONIAL_DAGGER = 55
    SHOWMAN = 56
    FORTUNE_TELLER = 57
    HIT_THE_ROAD = 58
    SWASHBUCKLER = 59
    FLOWER_POT = 60
    RID_THE_BUS = 61
    SHOOT_THE_MOON = 62
    SMEARED_JOKER = 64
    OOPS_ALL_6S = 65
    FOUR_FINGERS = 66
    GROS_MICHEL = 67
    STUNTMAN = 68
    HANGING_CHAD = 69
    DRIVERS_LICENSE = 70
    INVISIBLE_JOKER = 71
    ASTRONOMER = 72
    BURNT_JOKER = 73
    DUSK = 74
    THROWBACK = 75
    THE_IDOL = 76
    BRAINSTORM = 77
    SATELLITE = 78
    ROUGH_GEM = 79
    BLOODSTONE = 80
    ARROWHEAD = 81
    ONYX_AGATE = 82
    CANIO_BACKGROUND = 83
    TRIBOULET_BACKGROUND = 84
    YORICK_BACKGROUND = 85
    CHICOT_BACKGROUND = 86
    PERKEO_BACKGROUND = 87
    CERTIFICATE = 88
    BOOTSTRAPS = 89
    HOLOGRAM_REAL_FACE = 92
    CANIO_REAL_FACE = 93
    TRIBOULET_REAL_FACE = 94
    YORICK_REAL_FACE = 95
    CHICOT_REAL_FACE = 96
    PERKEO_REAL_FACE = 97
    EGG = 100
    BURGLAR = 101
    BLACKBOARD = 102
    RUNNER = 103
    ICE_CREAM = 104
    DNA = 105
    SPLASH = 106
    BLUE_JOKER = 107
    SIXTH_SENSE = 108
    CONSTELLATION = 109
    HIKER = 110
    FACELESS = 111
    GREEN_JOKER = 112
    SUPERPOSITION = 113
    TO_DO_LIST = 114
    CAVENDISH = 115
    CARD_SHARP = 116
    RED_CARD = 117
    MADNESS = 118
    SQUARE_JOKER = 119
    SEANCE = 120
    RIFF_RAFF = 121
    VAMPIRE = 122
    SHORTCUT = 123
    HOLOGRAM_BACKGROUND = 124
    VAGABOND = 125
    BARON = 126
    CLOUD_9 = 127
    ROCKET = 128
    OBELISK = 129
    MIDAS_MASK = 130
    LUCHADOR = 131
    PHOTOGRAPH = 132
    GIFT_CARD = 133
    TURTLE_BEAN = 134
    EROSION = 135
    RESERVED_PARKING = 136
    MAIL_IN_REBATE = 137
    TO_THE_MOON = 138
    HALLUCINATION = 139
    SLY_JOKER = 140
    WILY_JOKER = 141
    CLEVER_JOKER = 142
    DEVIOUS_JOKER = 143
    CRAFTY_JOKER = 144
    LUCKY_CAT = 145
    BASEBALL_CARD = 146
    BULL = 147
    DIET_COLA = 148
    TRADING_CARD = 149
    FLASH_CARD = 150
    POPCORN = 151
    RAMEN = 152
    SELTZER = 153
    SPARE_TROUSERS = 154
    CAMPFIRE = 155
    SMILEY_FACE = 156
    ANCIENT_JOKER = 157
    WALKIE_TALKIE = 158
    CASTLE = 159
