from enum import IntEnum


class Rank(IntEnum):
    TWO = 0
    THREE = 1
    FOUR = 2
    FIVE = 3
    SIX = 4
    SEVEN = 5
    EIGHT = 6
    NINE = 7
    TEN = 8
    JACK = 9
    QUEEN = 10
    KING = 11
    ACE = 12


class Suit(IntEnum):
    HEARTS = 0
    DIAMONDS = 1
    CLUBS = 2
    SPADES = 3


class Enhancement(IntEnum):
    NONE = 0
    STONE = 1
    GOLD = 2
    BONUS = 3
    MULT = 4
    WILD = 5
    LUCKY = 6
    GLASS = 7
    STEEL = 8


class Seal(IntEnum):
    NONE = 0
    GOLD = 1
    PURPLE = 2
    RED = 3
    BLUE = 4


class Edition(IntEnum):
    NONE = 0
    FOIL = 1
    HOLOGRAPHIC = 2
    POLYCHROME = 3


class CardFeatureTrainingType(IntEnum):
    RANK = 0
    SUIT = 1
    ENHANCEMENT = 2
    SEAL = 3
    EDITION = 4


class PokerHand(IntEnum):
    HIGH_CARD = 1
    PAIR = 2
    TWO_PAIR = 6
    THREE_OF_A_KIND = 3
    STRAIGHT = 7
    FLUSH = 8
    FULL_HOUSE = 9
    FOUR_OF_A_KIND = 4
    STRAIGHT_FLUSH = 10
    FIVE_OF_A_KIND = 5
    FLUSH_HOUSE = 11
    FLUSH_FIVE = 12


class Jokers(IntEnum):
    JOKER = 0
    CHAOS_THE_CLOWN = 1
    JOLLY_JOKER = 2
    ZANY_JOKER = 3
    MAD_JOKER = 4
    CRAZY_JOKER = 5
    DROLL_JOKER = 6
    HALF_JOKER = 7
    MERRY_ANDY = 8
    STONE_JOKER = 9
    JUGGLER = 10
    DRUNKARD = 11
    ACROBAT = 12
    SOCK_AND_BUSKIN = 13
    MIME = 14
    CREDIT_CARD = 15
    GREEDY_JOKER = 16
    LUSTY_JOKER = 17
    WRATHFUL_JOKER = 18
    GLUTTONOUS_JOKER = 19
    TROUBADOUR = 20
    BANNER = 21
    MYSTIC_SUMMIT = 22
    MARBLE_JOKER = 23
    LOYALTY_CARD = 24
    HACK = 25
    MISPRINT = 26
    STEEL_JOKER = 27
    RAISED_FIST = 28
    GOLDEN_JOKER = 29
    BLUEPRINT = 30
    GLASS_JOKER = 31
    SCARY_FACE = 32
    ABSTRACT_JOKER = 33
    DELAYED_GRATIFICATION = 34
    GOLDEN_TICKET = 35
    PAREIDOLIA = 36
    CARTOMANCER = 37
    EVEN_STEVEN = 38
    ODD_TODD = 39
    SCHOLER = 40
    BUSINESS_CARD = 41
    SUPERNOVA = 42
    MR_BONES = 43
    SEEING_DOUBLE = 44
    THE_DUO = 45
    THE_TRIO = 46
    THE_FAMILY = 47
    THE_ORDER = 48
    THE_TRIBE = 49
    X8_BALL = 50
    FIBONACCI = 51
    JOKER_STENCIL = 52
    SPACE_JOKER = 53
    MATADOR = 54
    CEREMONIAL_DAGGER = 55
    SHOWMAN = 56
    FORTUNE_TELLER = 57
    HIT_THE_ROAD = 58
    SWASHBUCKLER = 59
    FLOWER_POT = 60
    RID_THE_BUS = 61
    SHOOT_THE_MOON = 62
    SMEARED_JOKER = 64
    OOPS_ALL_6S = 65
    FOUR_FINGERS = 66
    GROS_MICHEL = 67
    STUNTMAN = 68
    HANGING_CHAD = 69
    DRIVERS_LICENSE = 70
    INVISIBLE_JOKER = 71
    ASTONOMER = 72
    BURNT_JOKER = 73
    DUSK = 74
    THROWBACK = 75
    THE_IDOL = 76
    BRAIN_STORM = 77
    SATELLITE = 78
    ROUGH_GEM = 79
    BLOODSTONE = 80
    ARROWHEAD = 81
    ONYX_AGATE = 82
    CANIO_BACKGROUND = 83
    TRIBOULET_BACKGROUND = 84
    YORICK_BACKGROUND = 85
    CHICOT_BACKGROUND = 86
    PERKEO_BACKGROUND = 87
    CERTIFICATE = 88
    BOOTSTRAPS = 89
    HOLOGRAM_FACE = 92
    CANIO_FACE = 93
    TRIBOULET_FACE = 94
    YORICK_FACE = 95
    CHICOT_FACE = 96
    PERKEO_FACE = 97
    EGG = 100
    BURGLAR = 101
    BLACKBOARD = 102
    RUNNER = 103
    ICE_CREAM = 104
    DNA = 105
    SPLASH = 106
    BLUE_JOKER = 107
    SIXTH_SENSE = 108
    CONSTELLATION = 109
    HIKER = 110
    FACELESS = 111
    GREEN_JOKER = 112
    SUPERPOSITION = 113
    TO_DO_LIST = 114
    CAVENDISH = 115
    CARD_SHARP = 116
    RED_CARD = 117
    MADNESS = 118
    SQUARE_JOKER = 119
    SEANCE = 120
    RIFF_RAFF = 121
    VAMPIRE = 122
    SHORTCUT = 123
    HOLOGRAM_BACKGROUND = 124
    VAGABOND = 125
    BARON = 126
    CLOUD_9 = 127
    ROCKET = 128
    OBELISK = 129
    MIDAS_MASK = 130
    LUCHADOR = 131
    PHOTOGRAPH = 132
    GIFT_CARD = 133
    TURTLE_BEAN = 134
    EROSION = 135
    RESERVED_PARKING = 136
    MAIL_IN_REBATE = 137
    TO_THE_MOON = 138
    HALLUCINATION = 139
    SLY_JOKER = 140
    WILY_JOKER = 141
    CLEVER_JOKER = 142
    DEVIOUS_JOKER = 143
    CRAFTY_JOKER = 144
    LUCKY_CAT = 145
    BASEBALL_CARD = 146
    BULL = 147
    DIET_COLA = 148
    TRADING_CARD = 149
    FLASH_CARD = 150
    POP_CORN = 151
    RAMEN = 152
    SELTZER = 153
    SPARE_TROUSERS = 154
    CAMPFIRE = 155
    SMILEY_FACE = 156
    ANCIENT_JOKER = 157
    WALKIE_TALKIE = 158
    CASTLE = 159
